diagnozy_zweryfikowane = [
    'dysfunkcje_owulacyjne',
    'policystyczne_jajniki',
    'zaburzenia_glikemii',
    'czynnik_tarczycowy',
    'nieprawidlowosci_w_obrebie_jajnikow',
    'obnizona_rezerwa_jajnikowa',
    'czynnik_jajowodowy_jednostronny',
    'zaburzenia_budowy_jamy_macicy',
    'wady_genetyczne',
    'inne_czynniki_endokrynologiczne',
    'endometrioza',
    'nieprawidlowosci_w_obrebie_macicy']
COLUMNS_RENAME = {
    '209_429_Średnia_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)'	:	'srednia_dlugosc_cyklu_miesiaczkowego'	,
    'Objaw_lub_procedura:AMENORRHOEA'	:	'amenorrhoea'	,
    '64_Czy_posiada_Pani_dzieci_biologiczne?:Liczba biologicznych dzieci'	:	'liczba_biologicznych_dzieci'	,
    '220_428_Czy_miesiączkuje_Pani_nieregularnie?'	:	'regularne_miesiaczki'	,
    '655_594_119_223_439_Czy_stosuje_Pani_środki_antykoncepcyjne?:ORAL_CONTRACEPTIVES'	:	'leki_antykoncepcyjne_doustne'	,
    '90_92_BMI'	:	'bmi'	,
    '210_430_Najkrótsza_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)'	:	'najkrotsza_dlugosc_cyklu_miesiaczkowego'	,
    '427_W_jakim_wieku_miała_Pani_pierwszą_miesiączkę?'	:	'wiek_pierwsza_miesiaczka'	,
    'patient_age'	:	'wiek_pacjentki'	,
    'Objaw_lub_procedura:EXCESSIVE_HAIR'	:	'nadmierne_owlosienie'	,
    'Objaw_lub_procedura:INSULIN_RESISTANCE'	:	'insulinoopornosc'	,
    '211_431_Najdłuższa_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)'	:	'najdluzsza_dlugosc_cyklu_miesiaczkowego'	,
    'Maksymalna_amplituda_cykli'	:	'maksymalna_amplituda_cykli'	,
    'Objaw_lub_procedura:PERSISTENT_RASH'	:	'wysypka'	,
    '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_ciaz'	:	'liczba_ciaz'	,
    'Objaw_lub_procedura:MOOD_CHANGES'	:	'zmiany_nastroju'	,
    'Objaw_lub_procedura:NUMBNESS'	:	'dretwienie'	,
    'Objaw_lub_procedura:WEAKNESS'	:	'oslabienie_organizmu'	,
    '213_Bóle_okołomiesiączkowe'	:	'bole_okolomiesiaczkowe'	,
    '214_Krwawienie_miesięczne_jest_zwykle'	:	'obfitosc_krwawienia'	,
    'Objaw_lub_procedura:WEIGHT_INCREASE_OF_5KG'	:	'wzrost_wagi'	,
    '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_poronien_obecny_partner'	:	'liczba_poronien_obecny_partner'	,
    '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_poronien'	:	'liczba_poronien'	,
    '102_Jak_długo_stara_się_Pani_zajść_w_ciążę?'	:	'dlugosc_staran_o_ciaze'	,
    'Objaw_lub_procedura:HIGH_BLOOD_PRESSURE'	:	'wysokie_cisnienie'	,
    'Objaw_lub_procedura:MENTAL_ISSUES'	:	'problemy_psychiczne'	,
    'Objaw_lub_procedura:HEAT_INTOLERANCE'	:	'nietolerancja_ciepla'	,
    'Objaw_lub_procedura:LOW_BLOOD_PRESSURE'	:	'niskie_cisnienie'	,
    'Objaw_lub_procedura:SPIT_OUT_OF_BREAST_NIPPLE'	:	'wyciek_z_gruczolu_mlecznego'	,
    '64_Czy_posiada_Pani_dzieci_biologiczne?:Liczba biologicznych dzieci z obecnym partnerem'	:	'liczba_biologicznych_dzieci_z_obecnym_partnerem'	,
    'Objaw_lub_procedura:EXCESSIVE_SWEATING'	:	'nadmierne_pocenie'	,
    '173_Czy_kiedykolwiek_zaobserwowała_Pani_niepokojące_objawy_związane_z_układem_moczowo_-_płciowym_(np._kamica_nerkowa_nietrzymanie_moczu_itp.)?'	:	'problemy_z_ukladem_moczowo_plciowym'	,
    'Objaw_lub_procedura:FREQUENT_URINATION'	:	'czeste_oddawanie_moczu'	,
    'Objaw_lub_procedura:STOOL_PROBLEMS'	:	'problemy_jelitowe'	,
    'Objaw_lub_procedura:REDUCTION_OF_SEX_DRIVE'	:	'zmniejszony_poped_seksualny'	,
    'Objaw_lub_procedura:INTERSTITIAL_BLEEDING'	:	'krwawienie_miedzyokresowe'	,
    '104_Jak_często_odbywa_Pani_stosunki_płciowe?'	:	'czestotliwosc_stosunkow_plciowych'	,
    'Objaw_lub_procedura:RECURRENT_VAGINITIS'	:	'nawracajace_zapalenie_pochwy'	,
    'Objaw_lub_procedura:TUMOR'	:	'guz'	,
    'Objaw_lub_procedura:ECTOPIC_PREGNANCY'	:	'ciaza_pozamaciczna'	,
    'Objaw_lub_procedura:INFLAMMATION_IN_PELVIS'	:	'stan_zapalny_miednicy'	,
    'Objaw_lub_procedura:INCREASED_BLEEDING_TIME'	:	'dlugie_gojenie_ran'	,
    'Objaw_lub_procedura:BLEEDING_AFTER_INTERCOURSE'	:	'krwawienie_po_stosunku'	,
    'Objaw_lub_procedura:MORE_THAN_2_MISCARRIAGES'	:	'wielokrotne_poronienie'	,

     'Objaw_lub_procedura:UNEXPLAINED_WEIGHT_LOSS'	:	'niewyjasniona_utrata_masy_ciala'	,
     'Objaw_lub_procedura:AUTOIMMUNE_DISEASES'	:	'choroba_autoimmunologiczna'



}

zmienne_platforma = {'dysfunkcje_owulacyjne': ['209_429_Średnia_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  'Objaw_lub_procedura:AMENORRHOEA'],
 'policystyczne_jajniki': ['64_Czy_posiada_Pani_dzieci_biologiczne?:Liczba biologicznych dzieci',
  '220_428_Czy_miesiączkuje_Pani_nieregularnie?',
  '655_594_119_223_439_Czy_stosuje_Pani_środki_antykoncepcyjne?:ORAL_CONTRACEPTIVES',
  '90_92_BMI',
  '210_430_Najkrótsza_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  '427_W_jakim_wieku_miała_Pani_pierwszą_miesiączkę?',
  'patient_age',
  'Objaw_lub_procedura:EXCESSIVE_HAIR',
  'Objaw_lub_procedura:INSULIN_RESISTANCE',
  '211_431_Najdłuższa_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  '209_429_Średnia_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  'Maksymalna_amplituda_cykli'],
 'zaburzenia_glikemii': ['Objaw_lub_procedura:PERSISTENT_RASH',
  '90_92_BMI',
  '220_428_Czy_miesiączkuje_Pani_nieregularnie?',
  'Objaw_lub_procedura:INSULIN_RESISTANCE',
  '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_ciaz',
  'Objaw_lub_procedura:MOOD_CHANGES',
  'Objaw_lub_procedura:NUMBNESS',
  'Objaw_lub_procedura:WEAKNESS',
  'Maksymalna_amplituda_cykli'],
 'inne_czynniki_endokrynologiczne': ['213_Bóle_okołomiesiączkowe',
  '214_Krwawienie_miesięczne_jest_zwykle',
  'patient_age',
  '220_428_Czy_miesiączkuje_Pani_nieregularnie?',
  '209_429_Średnia_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  '427_W_jakim_wieku_miała_Pani_pierwszą_miesiączkę?',
  'Maksymalna_amplituda_cykli',
  'Objaw_lub_procedura:WEAKNESS',
  'Objaw_lub_procedura:WEIGHT_INCREASE_OF_5KG',
  '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_poronien_obecny_partner',
  '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_poronien',
  'Objaw_lub_procedura:EXCESSIVE_HAIR',
  '102_Jak_długo_stara_się_Pani_zajść_w_ciążę?',
  'Objaw_lub_procedura:HIGH_BLOOD_PRESSURE',
  'Objaw_lub_procedura:MENTAL_ISSUES',
  'Objaw_lub_procedura:HEAT_INTOLERANCE',
  'Objaw_lub_procedura:LOW_BLOOD_PRESSURE',
  'Objaw_lub_procedura:RECURRENT_VAGINITIS',
  'Objaw_lub_procedura:AUTOIMMUNE_DISEASES',
  'Objaw_lub_procedura:INSULIN_RESISTANCE',
  'Objaw_lub_procedura:REDUCTION_OF_SEX_DRIVE',
  'Objaw_lub_procedura:UNEXPLAINED_WEIGHT_LOSS'],
 'czynnik_tarczycowy': ['Objaw_lub_procedura:SPIT_OUT_OF_BREAST_NIPPLE',
  '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_poronien',
  'patient_age',
  '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_ciaz',
  'Objaw_lub_procedura:WEIGHT_INCREASE_OF_5KG',
  '64_Czy_posiada_Pani_dzieci_biologiczne?:Liczba biologicznych dzieci z obecnym partnerem',
  '90_92_BMI',
  'Objaw_lub_procedura:EXCESSIVE_SWEATING',
  'Objaw_lub_procedura:WEAKNESS',
  'Objaw_lub_procedura:PERSISTENT_RASH',
  'Objaw_lub_procedura:EXCESSIVE_HAIR',
  'Objaw_lub_procedura:HEAT_INTOLERANCE',
  '102_Jak_długo_stara_się_Pani_zajść_w_ciążę?'],
 'nieprawidlowosci_w_obrebie_jajnikow': ['173_Czy_kiedykolwiek_zaobserwowała_Pani_niepokojące_objawy_związane_z_układem_moczowo_-_płciowym_(np._kamica_nerkowa_nietrzymanie_moczu_itp.)?',
  'Objaw_lub_procedura:FREQUENT_URINATION',
  '210_430_Najkrótsza_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  'Objaw_lub_procedura:STOOL_PROBLEMS',
  '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_poronien_obecny_partner',
  'Objaw_lub_procedura:REDUCTION_OF_SEX_DRIVE',
  '214_Krwawienie_miesięczne_jest_zwykle',
  'Maksymalna_amplituda_cykli',
  'Objaw_lub_procedura:INTERSTITIAL_BLEEDING',
  '209_429_Średnia_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  '211_431_Najdłuższa_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  '213_Bóle_okołomiesiączkowe',
  '104_Jak_często_odbywa_Pani_stosunki_płciowe?'],
 'obnizona_rezerwa_jajnikowa': ['patient_age',
  '210_430_Najkrótsza_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  '211_431_Najdłuższa_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  'Maksymalna_amplituda_cykli',
  '214_Krwawienie_miesięczne_jest_zwykle',
  '102_Jak_długo_stara_się_Pani_zajść_w_ciążę?',
  'Objaw_lub_procedura:RECURRENT_VAGINITIS',
  '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_poronien_obecny_partner',
  'Objaw_lub_procedura:HEAT_INTOLERANCE',
  '173_Czy_kiedykolwiek_zaobserwowała_Pani_niepokojące_objawy_związane_z_układem_moczowo_-_płciowym_(np._kamica_nerkowa_nietrzymanie_moczu_itp.)?',
  '213_Bóle_okołomiesiączkowe',
  'Objaw_lub_procedura:TUMOR'],
 'czynnik_jajowodowy_jednostronny': ['102_Jak_długo_stara_się_Pani_zajść_w_ciążę?',
  'patient_age',
  '104_Jak_często_odbywa_Pani_stosunki_płciowe?',
  '209_429_Średnia_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  '214_Krwawienie_miesięczne_jest_zwykle',
  '90_92_BMI',
  'Objaw_lub_procedura:MENTAL_ISSUES',
  '213_Bóle_okołomiesiączkowe',
  'Objaw_lub_procedura:ECTOPIC_PREGNANCY',
  '210_430_Najkrótsza_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  'Maksymalna_amplituda_cykli',
  '211_431_Najdłuższa_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)'],
 'zaburzenia_budowy_jamy_macicy': ['102_Jak_długo_stara_się_Pani_zajść_w_ciążę?',
  '209_429_Średnia_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  '210_430_Najkrótsza_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  '211_431_Najdłuższa_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  '213_Bóle_okołomiesiączkowe',
  'Maksymalna_amplituda_cykli',
  '104_Jak_często_odbywa_Pani_stosunki_płciowe?',
  'Objaw_lub_procedura:INFLAMMATION_IN_PELVIS',
  'Objaw_lub_procedura:AMENORRHOEA',
  'Objaw_lub_procedura:ECTOPIC_PREGNANCY'],
 'wady_genetyczne': ['121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_poronien_obecny_partner',
  '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_poronien',
  'patient_age',
  '102_Jak_długo_stara_się_Pani_zajść_w_ciążę?',
  '104_Jak_często_odbywa_Pani_stosunki_płciowe?',
  'Objaw_lub_procedura:INCREASED_BLEEDING_TIME',
  'Objaw_lub_procedura:HIGH_BLOOD_PRESSURE'],
 'endometrioza': ['213_Bóle_okołomiesiączkowe',
  'patient_age',
  '90_92_BMI',
  '209_429_Średnia_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  '102_Jak_długo_stara_się_Pani_zajść_w_ciążę?',
  '655_594_119_223_439_Czy_stosuje_Pani_środki_antykoncepcyjne?:ORAL_CONTRACEPTIVES',
  '214_Krwawienie_miesięczne_jest_zwykle',
  'Objaw_lub_procedura:FREQUENT_URINATION',
  'Objaw_lub_procedura:REDUCTION_OF_SEX_DRIVE',
  'Maksymalna_amplituda_cykli',
  '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_poronien',
  'Objaw_lub_procedura:WEAKNESS',
  'Objaw_lub_procedura:BLEEDING_AFTER_INTERCOURSE'],
 'nieprawidlowosci_w_obrebie_macicy': ['patient_age',
  '102_Jak_długo_stara_się_Pani_zajść_w_ciążę?',
  '209_429_Średnia_długość_cyklu_miesiączkowego_(liczba_dni_od_pierwszego_dnia_miesiączki_do_pierwszego_dnia_następnej_miesiączki)',
  '214_Krwawienie_miesięczne_jest_zwykle',
  'Maksymalna_amplituda_cykli',
  '64_Czy_posiada_Pani_dzieci_biologiczne?:Liczba biologicznych dzieci',
  'Objaw_lub_procedura:RECURRENT_VAGINITIS',
  '121_222_442_Ile_razy_była_Pani_w_ciąży?:liczba_ciaz',
  '90_92_BMI',
  '220_428_Czy_miesiączkuje_Pani_nieregularnie?',
  '213_Bóle_okołomiesiączkowe',
  'Objaw_lub_procedura:MORE_THAN_2_MISCARRIAGES',
  '427_W_jakim_wieku_miała_Pani_pierwszą_miesiączkę?']}
  