select rqs.id_client , rqs.id_meeting, rqs.id_process, rqs.who, rqs.when, rqs.version, rqs.survey_values, rqs.survey_results,
rqs.survey_values ->> 'no_wiggling_sperm':: text as no_wiggling_sperm,
rqs.survey_values ->> 'lack_male_of_stimulation':: text as lack_male_of_stimulation,
rqs.survey_values ->> 'no_alive_sperm':: text as no_alive_sperm,
rqs.survey_values ->> 'sperm_density_in_a_partner':: text as sperm_density_in_a_partner,
rqs.survey_values ->> 'high_sperm_fragmentation':: text as high_sperm_fragmentation,
rqs.survey_values ->> 'no_sperm_in_testicle':: text as no_sperm_in_testicle,
rqs.survey_values ->> 'no_liquid_sperm':: text as no_liquid_sperm,
rqs.survey_values ->> 'azoospermy':: text as azoospermy,
rqs.survey_values ->> 'testorone_deficiency':: text as testorone_deficiency,
rqs.survey_values ->> 'low_hialuron':: text as low_hialuron,
rqs.survey_values ->> 'high_oxydation_stres':: text as high_oxydation_stres,
rqs.survey_results ->> 'high_sperm_fragmentation':: text as s_results_high_sperm_fragmentation,
rqs.survey_results ->> 'sperm_density_in_a_partner':: text as s_results_sperm_density_in_a_partner,
rqs.survey_results ->> 'no_wiggling_sperm':: text as s_results_no_wiggling_sperm,
rqs.survey_results ->> 'no_alive_sperm':: text as s_results_no_alive_sperm,
rqs.survey_results ->> 'azoospermy':: text as s_results_azoospermy,
rqs.survey_results ->> 'low_hialuron':: text as s_results_low_hialuron,
rqs.survey_results ->> 'no_liquid_sperm':: text as s_results_no_liquid_sperm,
rqs.survey_results ->> 'no_sperm_in_testicle':: text as s_results_no_sperm_in_testicle
from public.report_qualifications_surveys rqs